#!/usr/bin/env node
"use strict";

const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const {
  PRESETS,
  applyCodexConfigFragment,
  applyProvider,
  createAppBridge,
  doctorProvider,
  exportAppBridgeState,
  exportCodexConfigFragment,
  installAppSurface,
  exportReport,
  readConfig,
  restoreCodexConfigBackup,
  restorePrevious,
  startMockProvider,
} = require("./core.js");


const PROVIDER_STUDIO_SERVER_PATCH = `

# Provider Studio API (installed by provider-studio-wave2 install-visible-ui)
import json as _ps_json
import re as _ps_re
import pathlib as _ps_pathlib
import tempfile as _ps_tempfile
import time as _ps_time
import urllib.parse as _ps_urlparse

_PROVIDER_STUDIO_MAX_BODY = 8192
_PROVIDER_STUDIO_IDS = {"openai", "openrouter", "local-openai-compatible", "open-bigmodel", "z-ai", "cliproxyapi"}

def _ps_root():
    webview_dir = _ps_pathlib.Path.cwd()
    app_dir = webview_dir.parent.parent
    root = app_dir / ".codex-linux" / "provider-studio"
    root.mkdir(parents=True, exist_ok=True)
    return root

def _ps_json_response(handler, status, payload):
    body = _ps_json.dumps(payload, indent=2).encode("utf-8")
    handler.send_response(status)
    handler.send_header("Content-Type", "application/json")
    handler.send_header("Content-Length", str(len(body)))
    handler.end_headers()
    handler.wfile.write(body)

def _ps_q(value):
    return _ps_json.dumps(str(value))

def _ps_provider_key(provider_id):
    return "provider-studio-" + "".join(ch if ch.isalnum() or ch in "_-" else "-" for ch in provider_id)

def _ps_display(provider_id):
    return {"openai":"OpenAI","openrouter":"OpenRouter","local-openai-compatible":"Local OpenAI-compatible","open-bigmodel":"open.bigmodel","z-ai":"z.ai","cliproxyapi":"CLIProxyAPI"}.get(provider_id, provider_id)

def _ps_wire(provider_id):
    return "responses" if provider_id in {"openai", "z-ai"} else "chat"

def _ps_is_loopback_url(value):
    try:
        parsed = _ps_urlparse.urlparse(value)
        host = (parsed.hostname or "").lower()
        return parsed.scheme in {"http", "https"} and (host == "localhost" or host == "::1" or host.startswith("127."))
    except Exception:
        return False

def _ps_fragment(payload):
    provider_id = payload["providerId"]
    key = _ps_provider_key(provider_id)
    lines = ["# Generated by Provider Studio from Codex Desktop Linux UI.", "# Secrets are intentionally omitted; set the referenced environment variable instead.", f"model = {_ps_q(payload['model'])}", f"model_provider = {_ps_q(key)}", "", f"[model_providers.{key}]", f"name = {_ps_q(_ps_display(provider_id))}", f"base_url = {_ps_q(payload['baseUrl'].rstrip('/'))}", f"wire_api = {_ps_q(_ps_wire(provider_id))}"]
    if payload.get("envKey"):
        lines.append(f"env_key = {_ps_q(payload['envKey'])}")
    return "\\n".join(lines) + "\\n"

def _ps_strip_root(lines, key):
    out=[]; in_root=True; pattern=_ps_re.compile(r"^\\s*" + _ps_re.escape(key) + r"\\s*=")
    for line in lines:
        if _ps_re.match(r"^\\s*\\[[^\\]]+\\]\\s*(?:#.*)?$", line):
            in_root=False
        if in_root and pattern.match(line):
            continue
        out.append(line)
    return out

def _ps_strip_section(lines, section):
    out=[]; skipping=False; target=_ps_re.compile(r"^\\s*\\[" + _ps_re.escape(section) + r"\\]\\s*(?:#.*)?$")
    for line in lines:
        is_section = _ps_re.match(r"^\\s*\\[[^\\]]+\\]\\s*(?:#.*)?$", line)
        if target.match(line):
            skipping=True; continue
        if skipping and is_section:
            skipping=False
        if not skipping:
            out.append(line)
    return out

def _ps_merge(existing, fragment):
    provider_key = next(line for line in fragment.splitlines() if line.startswith("model_provider =")).split("=",1)[1].strip().strip('"')
    lines = existing.replace("\\r\\n","\\n").replace("\\r","\\n").split("\\n") if existing else []
    if lines and lines[-1] == "": lines.pop()
    lines = _ps_strip_root(_ps_strip_root(lines, "model"), "model_provider")
    lines = _ps_strip_section(_ps_strip_section(lines, "profiles.provider-studio"), f"model_providers.{provider_key}")
    fragment_lines = fragment.strip().split("\\n")
    first_section = next((i for i, line in enumerate(fragment_lines) if line.strip().startswith("[")), len(fragment_lines))
    root_fragment = "\\n".join(fragment_lines[:first_section])
    section_fragment = "\\n".join(fragment_lines[first_section:])
    while lines and not lines[0].strip(): lines.pop(0)
    while lines and not lines[-1].strip(): lines.pop()
    body = ("\\n\\n" + "\\n".join(lines)) if lines else ""
    sections = ("\\n\\n" + section_fragment) if section_fragment else ""
    return root_fragment + body + sections + "\\n"

def _ps_validate(payload):
    if payload.get("providerId") not in _PROVIDER_STUDIO_IDS: raise ValueError("invalid providerId")
    for key in ("baseUrl", "model"):
        if not isinstance(payload.get(key), str) or not payload[key].strip(): raise ValueError(f"missing {key}")
    if payload.get("envKey") and not __import__("re").match(r"^[A-Za-z_][A-Za-z0-9_]*$", payload["envKey"]): raise ValueError("invalid envKey")
    if payload.get("managementKeyEnv") and not __import__("re").match(r"^[A-Za-z_][A-Za-z0-9_]*$", payload["managementKeyEnv"]): raise ValueError("invalid managementKeyEnv")
    if not (payload["baseUrl"].startswith("http://") or payload["baseUrl"].startswith("https://")): raise ValueError("invalid baseUrl")
    auth_mode = str(payload.get("authMode") or "env")
    if auth_mode not in {"env", "local-proxy"}: raise ValueError("invalid authMode")
    if auth_mode == "local-proxy" and not _ps_is_loopback_url(payload["baseUrl"]): raise ValueError("local proxy baseUrl must be localhost or loopback")
    if auth_mode == "local-proxy" and payload.get("managementUrl") and not _ps_is_loopback_url(payload["managementUrl"]): raise ValueError("managementUrl must be localhost or loopback")
    return {"providerId":payload["providerId"], "baseUrl":payload["baseUrl"].strip(), "model":payload["model"].strip(), "envKey":str(payload.get("envKey") or "").strip(), "authMode":auth_mode, "managementUrl":str(payload.get("managementUrl") or "").strip(), "managementKeyEnv":str(payload.get("managementKeyEnv") or "").strip()}

def _ps_apply(payload):
    payload=_ps_validate(payload); root=_ps_root(); fragment=_ps_fragment(payload)
    setup={"authMode":payload["authMode"],"credentialSource":{"type":"env","envKey":payload["envKey"]} if payload.get("envKey") else None,"localProxy":{"enabled":payload["authMode"]=="local-proxy","baseUrl":payload["baseUrl"]},"management":{"url":payload.get("managementUrl"),"keyEnv":payload.get("managementKeyEnv")}}
    if payload["authMode"] == "local-proxy": setup["credentialSource"]={"type":"proxy-managed"}
    state={"schemaVersion":1,"active":{"providerId":payload["providerId"],"modelId":payload["model"]},"provider":{"id":payload["providerId"],"displayName":_ps_display(payload["providerId"]),"baseUrl":payload["baseUrl"],"auth":{"type":"bearer","credentialRef":f"env:{payload['envKey']}" if payload.get("envKey") else None},"setup":setup},"setup":setup,"codex":{"model":payload["model"],"modelProvider":_ps_provider_key(payload["providerId"]),"wireApi":_ps_wire(payload["providerId"]),"configFragment":fragment}}
    (root/"state.json").write_text(_ps_json.dumps(state, indent=2)+"\\n", encoding="utf-8"); (root/"codex-config.provider-studio.toml").write_text(fragment, encoding="utf-8")
    home=_ps_pathlib.Path(os.environ.get("CODEX_HOME") or _ps_pathlib.Path.home()/".codex"); cfg=home/"config.toml"; cfg.parent.mkdir(parents=True, exist_ok=True)
    existing=cfg.read_text(encoding="utf-8") if cfg.exists() else ""; backup=cfg.with_name(cfg.name+".provider-studio-backup-"+_ps_time.strftime("%Y%m%dT%H%M%SZ")); backup.write_text(existing, encoding="utf-8"); backup.chmod(0o600)
    fd, tmp_name = _ps_tempfile.mkstemp(prefix=cfg.name+".", suffix=".tmp", dir=str(cfg.parent)); os.close(fd); tmp=_ps_pathlib.Path(tmp_name); tmp.write_text(_ps_merge(existing, fragment), encoding="utf-8"); tmp.chmod(0o600); tmp.replace(cfg)
    (home/"provider-studio.config.toml").write_text(f"model = {_ps_q(payload['model'])}\\nmodel_provider = {_ps_q(_ps_provider_key(payload['providerId']))}\\n", encoding="utf-8")
    return {"ok":True,"state":state,"configPath":str(cfg),"backupPath":str(backup),"fragmentPath":str(root/"codex-config.provider-studio.toml")}

def _ps_restore():
    home=_ps_pathlib.Path(os.environ.get("CODEX_HOME") or _ps_pathlib.Path.home()/".codex"); cfg=home/"config.toml"; backups=sorted(cfg.parent.glob(cfg.name+".provider-studio-backup-*"))
    if not backups: raise ValueError("no Provider Studio backup available")
    backup=backups[-1]; fd, tmp_name = _ps_tempfile.mkstemp(prefix=cfg.name+".", suffix=".tmp", dir=str(cfg.parent)); os.close(fd); tmp=_ps_pathlib.Path(tmp_name); tmp.write_text(backup.read_text(encoding="utf-8"), encoding="utf-8"); tmp.chmod(0o600); tmp.replace(cfg)
    root=_ps_root(); state={"schemaVersion":1,"active":None,"restoredFrom":str(backup)}; (root/"state.json").write_text(_ps_json.dumps(state, indent=2)+"\\n", encoding="utf-8")
    return {"ok":True,"configPath":str(cfg),"backupPath":str(backup),"state":state}
`;

function argValue(args, name) {
  const index = args.indexOf(name);
  return index === -1 ? null : args[index + 1] || null;
}

function tempRoot(args) {
  const requested = argValue(args, "--tmp-dir");
  if (requested) {
    fs.mkdirSync(requested, { recursive: true });
    return requested;
  }
  return fs.mkdtempSync(path.join(os.tmpdir(), "provider-studio-wave2-"));
}

function assertCondition(condition, message) {
  if (!condition) {
    throw new Error(message);
  }
}

function providerInput(overrides) {
  return {
    id: "mock-openai-compatible",
    displayName: "Mock OpenAI-compatible",
    baseUrl: overrides.baseUrl,
    modelListPath: "/v1/models",
    compatibility: "openai-compatible",
    authType: "bearer",
    apiKey: overrides.apiKey || "sk-smoke-secret-123",
    credentialRef: overrides.credentialRef || "env:MOCK_PROVIDER_API_KEY",
    defaultModel: overrides.defaultModel,
  };
}

async function runSmoke(args) {
  const root = tempRoot(args);
  const mock = await startMockProvider(["feedback-model-a", "feedback-model-b"]);
  try {
    const configPath = path.join(root, "codex-provider-studio.json");
    const reportPath = path.join(root, "provider-report.json");
    const provider = providerInput({ baseUrl: mock.baseUrl, defaultModel: "feedback-model-a" });
    const doctor = await doctorProvider(provider);
    assertCondition(PRESETS.length >= 3, "expected provider presets");
    assertCondition(doctor.status === "pass", "doctor did not pass");
    assertCondition(doctor.models.includes("feedback-model-a"), "model discovery failed");
    const applied = applyProvider(configPath, provider);
    assertCondition(applied.config.active.modelId === "feedback-model-a", "active model not applied");
    const report = exportReport(reportPath, { provider, doctor, applied });
    assertCondition(JSON.stringify(report).includes("[REDACTED]"), "report was not redacted");
    assertCondition(!fs.readFileSync(reportPath, "utf8").includes("sk-smoke-secret-123"), "raw secret leaked");
    restorePrevious(configPath);
    assertCondition(readConfig(configPath).active === null, "restore did not return previous config");
    console.log(`PASS smoke tmp=${root} report=${reportPath}`);
  } finally {
    await mock.close();
  }
}

async function runSwitchingSmoke(args) {
  const root = tempRoot(args);
  const mockA = await startMockProvider(["model-a1", "model-a2"]);
  const mockB = await startMockProvider(["model-b1", "model-b2"]);
  try {
    const configPath = path.join(root, "codex-provider-studio.json");
    const statePath = path.join(root, ".codex-linux", "provider-studio", "state.json");
    const providerA = providerInput({
      id: "mock-a",
      displayName: "Mock A",
      baseUrl: mockA.baseUrl,
      apiKey: "sk-a-secret",
      credentialRef: "env:MOCK_A_KEY",
      defaultModel: "model-a2",
    });
    providerA.id = "mock-a";
    providerA.displayName = "Mock A";
    const providerB = providerInput({
      id: "mock-b",
      displayName: "Mock B",
      baseUrl: mockB.baseUrl,
      apiKey: "sk-b-secret",
      credentialRef: "env:MOCK_B_KEY",
      defaultModel: "model-b1",
    });
    providerB.id = "mock-b";
    providerB.displayName = "Mock B";

    assertCondition((await doctorProvider(providerA)).status === "pass", "provider A doctor failed");
    assertCondition((await doctorProvider(providerB)).status === "pass", "provider B doctor failed");
    applyProvider(configPath, providerA);
    const afterA = readConfig(configPath).active;
    applyProvider(configPath, providerB);
    const afterB = readConfig(configPath).active;
    const bridgeState = exportAppBridgeState(statePath, readConfig(configPath));
    assertCondition(afterA.providerId === "mock-a" && afterA.modelId === "model-a2", "provider A not active");
    assertCondition(afterB.providerId === "mock-b" && afterB.modelId === "model-b1", "provider B not active");
    assertCondition(bridgeState.codex.model === "model-b1", "bridge state did not reflect provider B");
    assertCondition(!fs.readFileSync(statePath, "utf8").includes("sk-b-secret"), "bridge state leaked provider B secret");
    restorePrevious(configPath);
    const restored = readConfig(configPath).active;
    assertCondition(restored.providerId === "mock-a" && restored.modelId === "model-a2", "restore did not return provider A");
    console.log(`PASS switching tmp=${root} bridge=${statePath}`);
  } finally {
    await mockA.close();
    await mockB.close();
  }
}

async function runBridgeSmoke(args) {
  const root = tempRoot(args);
  const mockA = await startMockProvider(["bridge-model-a1", "bridge-model-a2"]);
  const mockB = await startMockProvider(["bridge-model-b1", "bridge-model-b2"]);
  try {
    const configPath = path.join(root, "codex-provider-studio.json");
    const reportPath = path.join(root, "provider-report.json");
    const statePath = path.join(root, ".codex-linux", "provider-studio", "state.json");
    const fragmentPath = path.join(root, "codex-config.provider-studio.toml");
    const bridge = createAppBridge({ configPath, reportPath, statePath });
    const providerA = providerInput({
      baseUrl: mockA.baseUrl,
      apiKey: "sk-a-secret",
      credentialRef: "env:MOCK_A_KEY",
      defaultModel: "bridge-model-a2",
    });
    providerA.id = "mock-a";
    providerA.displayName = "Mock A";
    const providerB = providerInput({
      baseUrl: mockB.baseUrl,
      apiKey: "sk-b-secret",
      credentialRef: "env:MOCK_B_KEY",
      defaultModel: "bridge-model-b1",
    });
    providerB.id = "mock-b";
    providerB.displayName = "Mock B";

    assertCondition((await bridge.handle("providerStudio.doctor", { provider: providerA })).status === "pass", "bridge doctor A failed");
    await bridge.handle("providerStudio.apply", { provider: providerA });
    await bridge.handle("providerStudio.apply", { provider: providerB });
    const state = await bridge.handle("providerStudio.exportAppBridgeState");
    const fragment = exportCodexConfigFragment(fragmentPath, readConfig(configPath));
    await bridge.handle("providerStudio.exportReport", { report: { state, active: readConfig(configPath).active } });
    assertCondition(state.active.providerId === "mock-b", "bridge did not switch to provider B");
    assertCondition(fragment.includes('model = "bridge-model-b1"'), "Codex fragment did not select provider B model");
    assertCondition(!fs.readFileSync(statePath, "utf8").includes("sk-b-secret"), "app bridge state leaked secret");
    assertCondition(!fs.readFileSync(reportPath, "utf8").includes("sk-b-secret"), "bridge report leaked secret");
    await bridge.handle("providerStudio.restore");
    assertCondition(readConfig(configPath).active.providerId === "mock-a", "bridge restore did not return provider A");
    console.log(`PASS bridge-smoke tmp=${root} state=${statePath} fragment=${fragmentPath}`);
  } finally {
    await mockA.close();
    await mockB.close();
  }
}

async function runRedactionCheck(args) {
  const root = tempRoot(args);
  const secret = argValue(args, "--secret") || "sk-feedback-SECRET-123";
  const reportPath = path.join(root, "redaction-report.json");
  const payload = {
    apiKey: secret,
    authorization: `Bearer ${secret}`,
    nested: { token: secret, visible: "provider-studio" },
  };
  exportReport(reportPath, payload);
  const reportText = fs.readFileSync(reportPath, "utf8");
  assertCondition(!reportText.includes(secret), "raw secret leaked");
  assertCondition(reportText.includes("[REDACTED]"), "redaction marker missing");
  console.log(`PASS redaction tmp=${root} report=${reportPath}`);
}

function runExportCodexFragment(args) {
  const configPath = argValue(args, "--config");
  const outPath = argValue(args, "--out");
  assertCondition(configPath, "--config is required");
  assertCondition(outPath, "--out is required");
  const fragment = exportCodexConfigFragment(outPath, readConfig(configPath));
  assertCondition(!/sk-[A-Za-z0-9_-]+/.test(fragment), "bridge fragment leaked secret-looking material");
  console.log(`PASS codex-fragment out=${outPath}`);
}


function runApplyCodexConfig(args) {
  const configPath = argValue(args, "--provider-config");
  const codexConfigPath = argValue(args, "--codex-config") || path.join(os.homedir(), ".codex", "config.toml");
  assertCondition(configPath, "--provider-config is required");
  const fragmentPath = argValue(args, "--fragment-out") || path.join(tempRoot(args), "codex-config.provider-studio.toml");
  const fragment = exportCodexConfigFragment(fragmentPath, readConfig(configPath));
  const result = applyCodexConfigFragment(codexConfigPath, fragment);
  console.log(`PASS apply-codex-config config=${result.configPath} backup=${result.backupPath} changed=${result.changed}`);
}

function runRestoreCodexConfig(args) {
  const codexConfigPath = argValue(args, "--codex-config") || path.join(os.homedir(), ".codex", "config.toml");
  const backupPath = argValue(args, "--backup");
  const result = restoreCodexConfigBackup(codexConfigPath, backupPath || undefined);
  console.log(`PASS restore-codex-config config=${result.configPath} backup=${result.backupPath}`);
}

function runInstallAppSurface(args) {
  const configPath = argValue(args, "--provider-config");
  const appDir = argValue(args, "--app-dir") || "/home/yun/tmp/codex-app-in-linux/upstream/codex-desktop-linux/codex-app";
  assertCondition(configPath, "--provider-config is required");
  const result = installAppSurface(appDir, readConfig(configPath));
  console.log(`PASS install-app-surface root=${result.root} state=${result.statePath} fragment=${result.fragmentPath} html=${result.htmlPath}`);
}


function injectProviderStudioScript(indexText) {
  if (indexText.includes('provider-studio-ui.js')) return indexText;
  if (!indexText.includes('</body>')) {
    throw new Error('Codex webview index.html is missing </body> anchor for Provider Studio injection.');
  }
  return indexText.replace('</body>', '    <script type="module" src="./provider-studio-ui.js"></script>\n  </body>');
}

function stripExistingProviderStudioServerPatch(serverText) {
  let next = serverText;
  next = next.replace(/\n*# Provider Studio API: small Linux-wrapper bridge for visible provider switching\.[\s\S]*?(?=\n# Provider Studio API \(installed by provider-studio-wave2 install-visible-ui\)|\nclass CodexWebviewHandler\(http\.server\.SimpleHTTPRequestHandler\):)/, '\n');
  next = next.replace(/\n*# Provider Studio API \(installed by provider-studio-wave2 install-visible-ui\)[\s\S]*?(?=\nclass CodexWebviewHandler\(http\.server\.SimpleHTTPRequestHandler\):)/, '\n');
  next = next.replace(/(class CodexWebviewHandler\(http\.server\.SimpleHTTPRequestHandler\):\n)(?:    def do_GET\(self\):[\s\S]*?\n\n)?(?:    def do_POST\(self\):[\s\S]*?\n\n)?/, '$1');
  return next;
}

function patchProviderStudioServer(serverText) {
  let next = stripExistingProviderStudioServerPatch(serverText);
  if (!next.includes('class CodexWebviewHandler(http.server.SimpleHTTPRequestHandler):\n')) {
    throw new Error('Codex webview-server.py is missing CodexWebviewHandler anchor for Provider Studio API injection.');
  }
  if (!next.includes('import os')) {
    if (!next.includes('import functools\n')) {
      throw new Error('Codex webview-server.py is missing import anchor for Provider Studio API injection.');
    }
    next = next.replace('import functools\n', 'import functools\nimport os\n');
  }
  next = next.replace('class CodexWebviewHandler(http.server.SimpleHTTPRequestHandler):\n', `${PROVIDER_STUDIO_SERVER_PATCH}\nclass CodexWebviewHandler(http.server.SimpleHTTPRequestHandler):\n`);
  const methods = `    def do_GET(self):\n        if self.path == "/provider-studio/api/state":\n            root = _ps_root(); state_path = root / "state.json"\n            if state_path.exists():\n                try: _ps_json_response(self, 200, _ps_json.loads(state_path.read_text(encoding="utf-8")))\n                except Exception as exc: _ps_json_response(self, 500, {"ok": False, "error": str(exc)})\n            else: _ps_json_response(self, 200, {"ok": True, "active": None, "message": "No Provider Studio selection applied yet."})\n            return\n        return super().do_GET()\n\n    def do_POST(self):\n        if self.path in ("/provider-studio/api/apply", "/provider-studio/api/restore"):\n            try:\n                if self.headers.get("content-type", "").split(";", 1)[0].strip().lower() != "application/json": raise ValueError("content-type must be application/json")\n                length = int(self.headers.get("content-length") or "0")\n                if length > _PROVIDER_STUDIO_MAX_BODY: raise ValueError("request body too large")\n                payload = _ps_json.loads(self.rfile.read(length).decode("utf-8") or "{}")\n                _ps_json_response(self, 200, _ps_apply(payload) if self.path.endswith("/apply") else _ps_restore())\n            except Exception as exc:\n                _ps_json_response(self, 400, {"ok": False, "error": str(exc)})\n            return\n        self.send_error(404)\n\n`;
  return next.replace('class CodexWebviewHandler(http.server.SimpleHTTPRequestHandler):\n', `class CodexWebviewHandler(http.server.SimpleHTTPRequestHandler):\n${methods}`);
}

function runInstallVisibleUi(args) {
  const appDir = argValue(args, '--app-dir') || '/home/yun/tmp/codex-app-in-linux/upstream/codex-desktop-linux/codex-app';
  const webviewDir = path.join(appDir, 'content', 'webview');
  const indexPath = path.join(webviewDir, 'index.html');
  const uiSource = path.join(__dirname, 'visible-ui.js');
  const uiTarget = path.join(webviewDir, 'provider-studio-ui.js');
  const serverPath = path.join(appDir, '.codex-linux', 'webview-server.py');
  assertCondition(fs.existsSync(indexPath), `missing ${indexPath}`);
  assertCondition(fs.existsSync(uiSource), `missing ${uiSource}`);
  assertCondition(fs.existsSync(serverPath), `missing ${serverPath}`);
  const nextIndex = injectProviderStudioScript(fs.readFileSync(indexPath, 'utf8'));
  const nextServer = patchProviderStudioServer(fs.readFileSync(serverPath, 'utf8'));
  fs.copyFileSync(uiSource, uiTarget);
  fs.writeFileSync(indexPath, nextIndex);
  fs.writeFileSync(serverPath, nextServer);
  console.log(`PASS install-visible-ui app=${appDir} ui=${uiTarget} server=${serverPath}`);
}

async function main() {
  const [command, ...args] = process.argv.slice(2);
  if (command === "smoke") {
    await runSmoke(args);
    return;
  }
  if (command === "switching-smoke") {
    await runSwitchingSmoke(args);
    return;
  }
  if (command === "bridge-smoke" || command === "app-bridge-smoke") {
    await runBridgeSmoke(args);
    return;
  }
  if (command === "redaction-check") {
    await runRedactionCheck(args);
    return;
  }
  if (command === "apply-codex-config") {
    runApplyCodexConfig(args);
    return;
  }
  if (command === "restore-codex-config") {
    runRestoreCodexConfig(args);
    return;
  }
  if (command === "install-app-surface") {
    runInstallAppSurface(args);
    return;
  }
  if (command === "install-visible-ui") {
    runInstallVisibleUi(args);
    return;
  }
  if (command === "export-codex-fragment") {
    runExportCodexFragment(args);
    return;
  }
  console.error("Usage: node provider-studio-wave2/cli.js <smoke|switching-smoke|bridge-smoke|redaction-check|export-codex-fragment|apply-codex-config|restore-codex-config|install-app-surface|install-visible-ui> [--tmp-dir DIR] [--config FILE --out FILE]");
  process.exitCode = 2;
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
});
