(() => {
  if (window.__providerStudioMounted) return;
  window.__providerStudioMounted = true;
  const css = `#provider-studio-fab{position:fixed;right:18px;bottom:18px;z-index:2147483647;border:1px solid rgba(255,255,255,.18);background:#111827;color:white;border-radius:999px;padding:10px 14px;font:13px system-ui;box-shadow:0 8px 28px rgba(0,0,0,.35);cursor:pointer}#provider-studio-panel{position:fixed;right:18px;bottom:64px;width:400px;max-width:calc(100vw - 36px);z-index:2147483647;background:#0b0f19;color:#e5e7eb;border:1px solid rgba(255,255,255,.16);border-radius:14px;box-shadow:0 20px 60px rgba(0,0,0,.5);font:13px system-ui;display:none;overflow:hidden}#provider-studio-panel.open{display:block}#provider-studio-panel header{display:flex;justify-content:space-between;align-items:center;padding:12px 14px;background:#111827;border-bottom:1px solid rgba(255,255,255,.12)}#provider-studio-panel main{padding:14px;display:grid;gap:10px}#provider-studio-panel label{display:grid;gap:5px;color:#cbd5e1}#provider-studio-panel input,#provider-studio-panel select{background:#020617;color:#e5e7eb;border:1px solid #334155;border-radius:8px;padding:8px;font:13px system-ui}#provider-studio-panel button{background:#2563eb;color:white;border:0;border-radius:8px;padding:9px 10px;font:13px system-ui;cursor:pointer}#provider-studio-panel button.secondary{background:#334155}#provider-studio-status{white-space:pre-wrap;background:#020617;border:1px solid #1e293b;border-radius:8px;padding:8px;color:#a7f3d0;max-height:150px;overflow:auto}`;
  const style = document.createElement('style'); style.textContent = css; document.documentElement.appendChild(style);
  const fab = document.createElement('button'); fab.id = 'provider-studio-fab'; fab.dataset.providerStudioOpen = 'true'; fab.type = 'button'; fab.textContent = 'Provider Studio';
  const panel = document.createElement('section'); panel.id = 'provider-studio-panel'; panel.dataset.providerStudioPanel = 'true'; panel.setAttribute('aria-label', 'Provider Studio provider and model switching');
  panel.innerHTML = `<header><strong>Provider Studio</strong><button class="secondary" id="ps-close" type="button">Close</button></header><main><label>Provider<select id="ps-provider"><option value="openai">OpenAI</option><option value="openrouter">OpenRouter</option><option value="local-openai-compatible">Local OpenAI-compatible</option></select></label><label>Base URL <input id="ps-base-url" value="https://api.openai.com" /></label><label>Model <input id="ps-model" value="gpt-5.5" /></label><label>Environment key for API key <input id="ps-env-key" value="OPENAI_API_KEY" /></label><button id="ps-apply" type="button" aria-label="Apply selection to Codex config">Apply selection to Codex config</button><button id="ps-restore" class="secondary" type="button" aria-label="Restore previous Codex config">Restore previous Codex config</button><button id="ps-refresh" class="secondary" type="button">Refresh state</button><div id="provider-studio-status">Loading...</div><small>Provider changes affect new Codex runtime work or after restart unless the app proves live switching.</small></main>`;
  document.body.append(panel, fab);
  const $ = (id) => panel.querySelector(id); const status = $('#provider-studio-status');
  const defaults = { openai: { baseUrl: 'https://api.openai.com', model: 'gpt-5.5', envKey: 'OPENAI_API_KEY' }, openrouter: { baseUrl: 'https://openrouter.ai/api', model: 'openai/gpt-5.5', envKey: 'OPENROUTER_API_KEY' }, 'local-openai-compatible': { baseUrl: 'http://127.0.0.1:11434', model: 'llama3.1', envKey: 'LOCAL_OPENAI_API_KEY' } };
  function setStatus(value) { status.textContent = typeof value === 'string' ? value : JSON.stringify(value, null, 2); }
  $('#ps-provider').addEventListener('change', () => { const d = defaults[$('#ps-provider').value]; $('#ps-base-url').value = d.baseUrl; $('#ps-model').value = d.model; $('#ps-env-key').value = d.envKey; });
  async function call(path, payload) { const res = await fetch(path, payload ? { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(payload) } : { cache: 'no-store' }); return res.json(); }
  async function refresh() { try { setStatus(await call('/provider-studio/api/state')); } catch (e) { setStatus(`state read failed: ${e.message}`); } }
  async function apply() { const payload = { providerId: $('#ps-provider').value, baseUrl: $('#ps-base-url').value.trim(), model: $('#ps-model').value.trim(), envKey: $('#ps-env-key').value.trim() }; setStatus('Applying...'); try { setStatus(await call('/provider-studio/api/apply', payload)); } catch (e) { setStatus(`apply failed: ${e.message}`); } }
  async function restore() { setStatus('Restoring...'); try { setStatus(await call('/provider-studio/api/restore', {})); } catch (e) { setStatus(`restore failed: ${e.message}`); } }
  fab.addEventListener('click', () => { panel.classList.toggle('open'); refresh(); }); $('#ps-close').addEventListener('click', () => panel.classList.remove('open')); $('#ps-refresh').addEventListener('click', refresh); $('#ps-apply').addEventListener('click', apply); $('#ps-restore').addEventListener('click', restore);
})();
